# Generated by Django 5.0.2 on 2024-03-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='endereco',
        ),
        migrations.AddField(
            model_name='empresa',
            name='enderecos',
            field=models.ManyToManyField(related_name='empresa_enderecos', to='cadastros.endereco'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='enderecos',
            field=models.ManyToManyField(related_name='pessoa_enderecos', to='cadastros.endereco'),
        ),
        migrations.AddField(
            model_name='produto',
            name='atributos',
            field=models.ManyToManyField(related_name='produtos', to='cadastros.atributo'),
        ),
    ]
