# Generated by Django 5.0.2 on 2024-07-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_atributo_remove_empresa_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('urlImagem', models.URLField()),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='atributos',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='enderecos',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='proprietario',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='template',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='imagemtemplate',
            name='template',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='enderecos',
        ),
        migrations.AddField(
            model_name='endereco',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='cadastros.pessoa'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pessoa')),
                ('itens', models.ManyToManyField(related_name='item_saidas', to='cadastros.item')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pessoa')),
                ('itens', models.ManyToManyField(related_name='item_entradas', to='cadastros.item')),
                ('servico', models.ManyToManyField(related_name='entradas', to='cadastros.servico')),
            ],
        ),
        migrations.DeleteModel(
            name='Atributo',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='ImagemTemplate',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
