# Generated by Django 5.0.2 on 2024-12-02 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_entrada_cadastrado_por_pessoa_cadastrado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='itens',
        ),
        migrations.RemoveField(
            model_name='saida',
            name='itens',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='servico',
        ),
        migrations.AddField(
            model_name='entrada',
            name='aberta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='saida',
            name='aberta',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ItemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('entrada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_entrada', to='cadastros.entrada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto')),
                ('saida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_saida', to='cadastros.saida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('entrada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_servico_entrada', to='cadastros.entrada')),
                ('saida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_servico_saida', to='cadastros.saida')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.servico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
