# Generated by Django 5.0.2 on 2024-12-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_remove_entrada_itens_remove_saida_itens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saida',
            name='fechar_saida',
            field=models.BooleanField(default=False, verbose_name='Fechar saída'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
